In [ ]:
import polars as pl

In [ ]:
def load_user_embeddings() -> pl.DataFrame:
    splits = {'train': 'data/train-00000-of-00001.parquet', 'test_warm': 'data/test_warm-00000-of-00001.parquet', 'test_cold': 'data/test_cold-00000-of-00001.parquet'}
    df_train = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-User-Embeddings/" + splits["train"])
    df_test_warm = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-User-Embeddings/" + splits["test_warm"])
    df_test_cold = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-User-Embeddings/" + splits["test_cold"])
    
    df_train = df_train.with_columns(pl.lit("train").alias("split"))
    df_test_warm = df_test_warm.with_columns(pl.lit("test_warm").alias("split"))
    df_test_cold = df_test_cold.with_columns(pl.lit("test_cold").alias("split"))

    return pl.concat([df_train, df_test_warm, df_test_cold], how="vertical")

def load_dev_data() -> pl.DataFrame:
    splits = {'train': 'data/train-00000-of-00001.parquet', 'test': 'data/test-00000-of-00001.parquet'}
    df_train = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-Dataset/" + splits["train"])
    df_test = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-Dataset/" + splits["test"])
    df_train = df_train.with_columns(pl.lit("train").alias("split_dev"))
    df_test = df_test.with_columns(pl.lit("test").alias("split_dev"))
    return pl.concat([df_train, df_test], how="vertical")

def load_user_metadata() -> pl.DataFrame:
    df = pl.read_parquet("hf://datasets/talkpl-ai/TalkPlayData-Challenge-User-Metadata/data/all_users-00000-of-00001.parquet")
    return df

In [3]:
df = load_user_embeddings()
df.head()

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬───────┐
│ user_id                         ┆ cf-bpr                          ┆ split │
│ ---                             ┆ ---                             ┆ ---   │
│ str                             ┆ list[f64]                       ┆ str   │
╞═════════════════════════════════╪═════════════════════════════════╪═══════╡
│ 5e0690dc-ffcf-41c1-94e5-2fdafc… ┆ [0.001394, -0.001117, … 0.0000… ┆ train │
│ c26f5e1c-f352-455f-aaeb-bb2d59… ┆ [-0.000811, -0.001889, … 0.002… ┆ train │
│ 3b21a6b1-338d-42c8-aa9c-236835… ┆ [-0.003471, 0.005971, … -0.002… ┆ train │
│ a95c3a54-2962-4fa9-80ff-1bb091… ┆ [0.000716, -0.009839, … -0.000… ┆ train │
│ 585f4782-6f0f-4fce-8823-373ca6… ┆ [-0.004334, 0.002392, … 0.0012… ┆ train │
└─────────────────────────────────┴─────────────────────────────────┴───────┘

In [4]:
df.shape

(9091, 3)

# 単変量解析

# split

In [5]:
df.group_by("split").agg(pl.count())

C:\Users\ken05\AppData\Local\Temp\ipykernel_4656\1021667543.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("split").agg(pl.count())

shape: (3, 2)
┌───────────┬───────┐
│ split     ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ test_cold ┆ 129   │
│ test_warm ┆ 371   │
│ train     ┆ 8591  │
└───────────┴───────┘

## user_id

In [6]:
df["user_id"][0]

'5e0690dc-ffcf-41c1-94e5-2fdafc4bd4ed'

In [7]:
df["user_id"].value_counts().sort("count", descending=True).head()

shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ user_id                         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ fa891983-f810-4769-8d11-3d7315… ┆ 2     │
│ 80fd5bb2-e9d9-4a02-b86d-e7b2aa… ┆ 2     │
│ 39fdc5d3-37c0-4f7a-9bd5-0a7a93… ┆ 2     │
│ b3475bae-7bc5-49b2-a2d4-326d8a… ┆ 2     │
│ b3a298af-dd88-4809-8682-e004fe… ┆ 2     │
└─────────────────────────────────┴───────┘

In [8]:
user_id_count = df["user_id"].value_counts().rename({"count": "appearance"})
user_id_count.group_by("appearance").agg(pl.len())

shape: (2, 2)
┌────────────┬──────┐
│ appearance ┆ len  │
│ ---        ┆ ---  │
│ u32        ┆ u32  │
╞════════════╪══════╡
│ 1          ┆ 8349 │
│ 2          ┆ 371  │
└────────────┴──────┘

In [9]:
user_id_count_is2 = user_id_count.filter(pl.col("appearance") == 2)
df.filter((pl.col("split") == "test_warm") & (pl.col("user_id").is_in(user_id_count_is2["user_id"]))).shape

C:\Users\ken05\AppData\Local\Temp\ipykernel_4656\1698753904.py:2: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  df.filter((pl.col("split") == "test_warm") & (pl.col("user_id").is_in(user_id_count_is2["user_id"]))).shape

(371, 3)

In [10]:
df.group_by(["split", "user_id"]).agg(pl.len()).sort("len", descending=True).head()

shape: (5, 3)
┌───────────┬─────────────────────────────────┬─────┐
│ split     ┆ user_id                         ┆ len │
│ ---       ┆ ---                             ┆ --- │
│ str       ┆ str                             ┆ u32 │
╞═══════════╪═════════════════════════════════╪═════╡
│ test_warm ┆ 704cf4a0-bad3-4e4b-b165-7b77b6… ┆ 1   │
│ train     ┆ 21f98a49-610d-4413-bd48-cb5efe… ┆ 1   │
│ train     ┆ 89d056fe-2af1-4842-bf99-40a164… ┆ 1   │
│ train     ┆ 50e2e609-cbc4-4144-8097-d95ec5… ┆ 1   │
│ test_warm ┆ a317f5c9-616b-4482-b62a-01fda1… ┆ 1   │
└───────────┴─────────────────────────────────┴─────┘

# cf-bpr

In [11]:
df["cf-bpr"].head()

shape: (10,)
Series: 'cf-bpr' [list[f64]]
[
	[0.001394, -0.001117, … 0.00007]
	[-0.000811, -0.001889, … 0.00271]
	[-0.003471, 0.005971, … -0.002615]
	[0.000716, -0.009839, … -0.000072]
	[-0.004334, 0.002392, … 0.001241]
	[0.000863, -0.002547, … 0.00004]
	[-0.000148, -0.000918, … -0.007247]
	[0.012863, 0.000981, … -0.008897]
	[0.003417, 0.00174, … 0.004345]
	[0.005837, -0.006638, … -0.002279]
]

In [12]:
df.with_columns(pl.col("cf-bpr").list.len().alias("emb_len")).select(pl.col("emb_len").unique())

shape: (2, 1)
┌─────────┐
│ emb_len │
│ ---     │
│ u32     │
╞═════════╡
│ 0       │
│ 128     │
└─────────┘

In [13]:
cf_bpr_len = df.with_columns(pl.col("cf-bpr").list.len().alias("emb_len"))
cf_bpr_len.select(["emb_len", "split"]).group_by(["emb_len", "split"]).agg(pl.len())

shape: (4, 3)
┌─────────┬───────────┬──────┐
│ emb_len ┆ split     ┆ len  │
│ ---     ┆ ---       ┆ ---  │
│ u32     ┆ str       ┆ u32  │
╞═════════╪═══════════╪══════╡
│ 128     ┆ test_cold ┆ 25   │
│ 128     ┆ train     ┆ 8591 │
│ 0       ┆ test_cold ┆ 104  │
│ 128     ┆ test_warm ┆ 371  │
└─────────┴───────────┴──────┘

In [14]:
cf_bpr_len.filter((pl.col("emb_len") == 128) & (pl.col("split") == "test_cold")).head(10)

shape: (10, 4)
┌─────────────────────────────────┬─────────────────────────────────┬───────────┬─────────┐
│ user_id                         ┆ cf-bpr                          ┆ split     ┆ emb_len │
│ ---                             ┆ ---                             ┆ ---       ┆ ---     │
│ str                             ┆ list[f64]                       ┆ str       ┆ u32     │
╞═════════════════════════════════╪═════════════════════════════════╪═══════════╪═════════╡
│ 0b26e17b-0627-45e3-baa1-aa285a… ┆ [0.001365, 0.002224, … -0.0026… ┆ test_cold ┆ 128     │
│ 9a003c54-6d2d-416e-bef1-dc1d05… ┆ [-0.000827, -0.002198, … -0.00… ┆ test_cold ┆ 128     │
│ cc31cceb-9477-45af-97f6-c64889… ┆ [-0.0035, -0.004494, … -0.0015… ┆ test_cold ┆ 128     │
│ 1b6cf64c-611b-419e-b9d6-f43f7d… ┆ [0.00001, 0.002219, … -0.00284… ┆ test_cold ┆ 128     │
│ fba103ec-2939-402e-8560-5a57a8… ┆ [-0.00345, -0.002423, … 0.0016… ┆ test_cold ┆ 128     │
│ b74bae1a-56ad-4cc5-95c1-f72bd8… ┆ [0.000072, 0.001815, … -0.0037… ┆ test_cold ┆ 128     │
│ 777529e6-7f1a-4b7c-b30b-a2bba9… ┆ [-0.014244, 0.020431, … 0.0054… ┆ test_cold ┆ 128     │
│ 0cdbcde9-afb1-4ec7-8356-51d324… ┆ [-0.011164, 0.008934, … -0.001… ┆ test_cold ┆ 128     │
│ db93bf83-27ca-47e8-81b3-b43396… ┆ [-0.003385, 0.003455, … 0.0018… ┆ test_cold ┆ 128     │
│ 73cfb11f-cca6-4ece-aa4f-4f1e6b… ┆ [0.003848, 0.001205, … -0.0060… ┆ test_cold ┆ 128     │
└─────────────────────────────────┴─────────────────────────────────┴───────────┴─────────┘

In [15]:
cf_bpr_len.filter((pl.col("emb_len") == 0) & (pl.col("split") == "test_cold")).head(10)

shape: (10, 4)
┌─────────────────────────────────┬───────────┬───────────┬─────────┐
│ user_id                         ┆ cf-bpr    ┆ split     ┆ emb_len │
│ ---                             ┆ ---       ┆ ---       ┆ ---     │
│ str                             ┆ list[f64] ┆ str       ┆ u32     │
╞═════════════════════════════════╪═══════════╪═══════════╪═════════╡
│ e1dac513-ee13-40a1-9bb1-fa69e0… ┆ []        ┆ test_cold ┆ 0       │
│ 1b8d08b3-f103-4af7-a87b-f3fee8… ┆ []        ┆ test_cold ┆ 0       │
│ bb95b750-f90c-4220-bf14-544345… ┆ []        ┆ test_cold ┆ 0       │
│ b4c46ecb-3085-4525-875b-a8fa53… ┆ []        ┆ test_cold ┆ 0       │
│ 653f918b-28b5-46cc-8cbd-bea194… ┆ []        ┆ test_cold ┆ 0       │
│ 7fb1c25a-8b8a-4270-a1b9-ca5e54… ┆ []        ┆ test_cold ┆ 0       │
│ 9c9c74f3-e20b-4976-969b-cdcf43… ┆ []        ┆ test_cold ┆ 0       │
│ 4a79be1f-321a-4352-8ddf-f3c08a… ┆ []        ┆ test_cold ┆ 0       │
│ 2849bce6-9b66-402f-b49b-948e76… ┆ []        ┆ test_cold ┆ 0       │
│ 7f42662a-d8ef-4c95-8bc2-72c4b4… ┆ []        ┆ test_cold ┆ 0       │
└─────────────────────────────────┴───────────┴───────────┴─────────┘

### cf-bprの0次元の謎をほかのデータと照らし合わせてみる

In [16]:
df_metadata = load_user_metadata()
df_dev = load_dev_data()

df_all = (
    df
    .join(df_metadata, on="user_id", how="left")
    .join(df_dev, on="user_id", how="left")
)
df_all.head(3)

shape: (3, 15)
┌─────────────┬─────────────┬───────┬─────┬───┬─────────────┬─────────────┬────────────┬───────────┐
│ user_id     ┆ cf-bpr      ┆ split ┆ age ┆ … ┆ conversatio ┆ conversatio ┆ goal_progr ┆ split_dev │
│ ---         ┆ ---         ┆ ---   ┆ --- ┆   ┆ n_goal      ┆ ns          ┆ ess_assess ┆ ---       │
│ str         ┆ list[f64]   ┆ str   ┆ i64 ┆   ┆ ---         ┆ ---         ┆ ments      ┆ str       │
│             ┆             ┆       ┆     ┆   ┆ struct[3]   ┆ list[struct ┆ ---        ┆           │
│             ┆             ┆       ┆     ┆   ┆             ┆ [4]]        ┆ list[struc ┆           │
│             ┆             ┆       ┆     ┆   ┆             ┆             ┆ t[2]]      ┆           │
╞═════════════╪═════════════╪═══════╪═════╪═══╪═════════════╪═════════════╪════════════╪═══════════╡
│ 5e0690dc-ff ┆ [0.001394,  ┆ train ┆ 19  ┆ … ┆ {"H","find  ┆ [{"Can you  ┆ [{null,1}, ┆ train     │
│ cf-41c1-94e ┆ -0.001117,  ┆       ┆     ┆   ┆ multiple    ┆ show me     ┆ {"DOES_NOT ┆           │
│ 5-2fdafc…   ┆ … 0.0000…   ┆       ┆     ┆   ┆ songs from… ┆ indie pop   ┆ _MOVE_TOW… ┆           │
│             ┆             ┆       ┆     ┆   ┆             ┆ a…          ┆            ┆           │
│ c26f5e1c-f3 ┆ [-0.000811, ┆ train ┆ 25  ┆ … ┆ {"H","find  ┆ [{"I'm      ┆ [{null,1}, ┆ train     │
│ 52-455f-aae ┆ -0.001889,  ┆       ┆     ┆   ┆ multiple    ┆ interested  ┆ {"MOVES_TO ┆           │
│ b-bb2d59…   ┆ … 0.002…    ┆       ┆     ┆   ┆ songs from… ┆ in          ┆ WARD_GOAL… ┆           │
│             ┆             ┆       ┆     ┆   ┆             ┆ exploring…  ┆            ┆           │
│ 3b21a6b1-33 ┆ [-0.003471, ┆ train ┆ 23  ┆ … ┆ {"H","Ident ┆ [{"I'm      ┆ [{null,1}, ┆ train     │
│ 8d-42c8-aa9 ┆ 0.005971, … ┆       ┆     ┆   ┆ ify a       ┆ trying to   ┆ {"MOVES_TO ┆           │
│ c-236835…   ┆ -0.002…     ┆       ┆     ┆   ┆ specific    ┆ find some   ┆ WARD_GOAL… ┆           │
│             ┆             ┆       ┆     ┆   ┆ arti…       ┆ mus…        ┆            ┆           │
└─────────────┴─────────────┴───────┴─────┴───┴─────────────┴─────────────┴────────────┴───────────┘

In [ ]:
df_metadata["user_id"].value_counts().sort("count", descending=True).head()

AttributeError: 'DataFrame' object has no attribute 'user_id'