In [1]:
import polars as pl
from src.load_data import load_main_data

In [3]:
df = load_main_data.load_dev_data()
df.head(1)

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ session_id ┆ user_id    ┆ session_da ┆ user_prof ┆ conversat ┆ conversat ┆ goal_prog ┆ split_dev │
│ ---        ┆ ---        ┆ te         ┆ ile       ┆ ion_goal  ┆ ions      ┆ ress_asse ┆ ---       │
│ str        ┆ str        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ssments   ┆ str       │
│            ┆            ┆ str        ┆ struct[9] ┆ struct[3] ┆ list[stru ┆ ---       ┆           │
│            ┆            ┆            ┆           ┆           ┆ ct[4]]    ┆ list[stru ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ ct[2]]    ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 9c337a02-1 ┆ 64ea97af-b ┆ 2011-12-26 ┆ {20,"20s" ┆ {"H","The ┆ [{"I want ┆ [{null,1} ┆ train     │
│ 5b1-408f-8 ┆ bc6-4756-a ┆            ┆ ,"BR","Br ┆ listener  ┆ to        ┆ , {"MOVES ┆           │
│ 103-c2f945 ┆ c94-b93104 ┆            ┆ azil","fe ┆ wants to  ┆ discover  ┆ _TOWARD_G ┆           │
│ …          ┆ …          ┆            ┆ mal…      ┆ ex…       ┆ some new… ┆ OAL…      ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [23]:
def preprocess(df: pl.DataFrame) -> pl.DataFrame:
    df = (
        df
        .explode("conversations")
        .unnest("conversations")
        .drop("user_id")
        .unnest("user_profile")
    )

    df_user = df.filter(pl.col("role") == "user")

    # ターゲットの抽出
    df_music = (
        df
        .filter(pl.col("role") == "music")
        .select(["session_id", "user_id", "turn_number", "content"])
        .rename({"content": "ans_track_id"})
    )

    ret_df = df_user.join(df_music, on=["session_id", "user_id", "turn_number"])

    return ret_df

df_processed = preprocess(df)

In [24]:
df_processed.head(1)

shape: (1, 19)
┌────────────┬────────────┬─────┬───────────┬───┬────────────┬────────────┬───────────┬────────────┐
│ session_id ┆ session_da ┆ age ┆ age_group ┆ … ┆ turn_numbe ┆ goal_progr ┆ split_dev ┆ ans_track_ │
│ ---        ┆ te         ┆ --- ┆ ---       ┆   ┆ r          ┆ ess_assess ┆ ---       ┆ id         │
│ str        ┆ ---        ┆ i64 ┆ str       ┆   ┆ ---        ┆ ments      ┆ str       ┆ ---        │
│            ┆ str        ┆     ┆           ┆   ┆ i64        ┆ ---        ┆           ┆ str        │
│            ┆            ┆     ┆           ┆   ┆            ┆ list[struc ┆           ┆            │
│            ┆            ┆     ┆           ┆   ┆            ┆ t[2]]      ┆           ┆            │
╞════════════╪════════════╪═════╪═══════════╪═══╪════════════╪════════════╪═══════════╪════════════╡
│ 9c337a02-1 ┆ 2011-12-26 ┆ 20  ┆ 20s       ┆ … ┆ 1          ┆ [{null,1}, ┆ train     ┆ 81d9f1d9-3 │
│ 5b1-408f-8 ┆            ┆     ┆           ┆   ┆            ┆ {"MOVES_TO ┆           ┆ b22-4836-9 │
│ 103-c2f945 ┆            ┆     ┆           ┆   ┆            ┆ WARD_GOAL… ┆           ┆ f06-2140e9 │
│ …          ┆            ┆     ┆           ┆   ┆            ┆            ┆           ┆ …          │
└────────────┴────────────┴─────┴───────────┴───┴────────────┴────────────┴───────────┴────────────┘